---
- hosts: all
  become: true
  remote_user: dietpi   # User to log into to run the playbook tasks
  tags: boot
  vars:
    NORMAL_USER_NAME: "ansible"
  tasks:
    - name: "Create a secondary, non-root user"
      ansible.builtin.user:
        name: "{{ NORMAL_USER_NAME }}"
        comment: ''
        # Password hash generated on https://www.mkpasswd.net/index.php using sha-512 and Category: sha
        password: "$6$Yncz4m42B2o9IDWO$Lsi4LWSi3OnvEmp92gVmwKquey4WuYnB./8SwsN7uxhpFh2OKVA7rJWtdf/hsbvkZxUIKc.ev6xpZAd9OiSNU."
        groups:
          - sudo
          - root
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_type: ed25519
        create_home: "no"
        shell: /bin/bash
    - name: "Add user ({{ NORMAL_USER_NAME }}) to sudoers"
      lineinfile:
        dest: /etc/sudoers
        regexp: "{{ NORMAL_USER_NAME }} ALL"
        line: "{{ NORMAL_USER_NAME }} ALL=(ALL) ALL"
        state: present

    - name: Add authorized key to user ({{ NORMAL_USER_NAME }}) 
      authorized_key:
        user: "{{ NORMAL_USER_NAME }}"
        key: "{{ lookup('file', './files/ansible.id_ed25519.pub') }}"

- hosts: all
  # become: true
  # become_user: ansible
  tags: apt,pkg
  tasks:
    - name: Install htop
      package:
        name: htop
        state: latest

- hosts: all
  become: true
  become_user: ansible
  tags: always
  tasks:
    - name: Update cache & Upgrade all packages
      register: update_sys
      apt:
        update_cache: true
        upgrade: dist
        autoremove: true
        autoclean: true
    - name: Display the last line of the previous task to check the stats
      debug:
        msg:  "{{update_sys.stdout_lines|last}}"
