[raspis]
raspihole ansible_host=raspihole.home
raspodin ansible_host=raspodin.home    ansible_port=8022

[laptops]
# asus-rog-flow13.home
# rog-zephyrus.home
# switch-alpha.home

[rpi_kube_control]
; rasphermes.local  ansible_connection=ssh
raspworker10 ansible_host=raspworker10.local ansible_connection=ssh

[rpi_kube_workers]
; Remove rasphermes as kube control, not enough RAM memory
; raspworker[11:14].local  ansible_connection=ssh
raspworker11 ansible_host=raspworker11.local
; raspworker11.local  ansible_connection=ssh
; raspworker[21:24].local  ansible_connection=ssh
# raspworker[31:34].local  ansible_connection=ssh
# raspworker[41:44].local  ansible_connection=ssh
# raspworker[51:54].local  ansible_connection=ssh

[rpi_kube:children]
rpi_kube_control
rpi_kube_workers


[rpis:children]
raspis
rpi_kube

[all:vars]
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_user=dietpi
